server:
  port: 8020
#spring:
#  application:
#    name: config-client
#cloud:
#  config:
#    name: application-dev
#    label: master
#    profile: dev
#    uri: http://localhost:8010/
#    discovery:
#      enabled: true
#      service-id: config-server
#    enable: true
#    fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
management:
  security:
    enabled: false